/**
 * Sample exam configurations for testing
 */

import { ExamConfiguration } from '../types';

export const SAMPLE_EXAMS: ExamConfiguration[] = [
  {
    id: 'math-101-midterm',
    title: 'Pre-Calculus Midterm Exam',
    description: 'A comprehensive exam covering algebra, trigonometry, and basic calculus concepts.',
    totalTimeMs: 120 * 60 * 1000, // 120 minutes
    adaptiveDifficulty: true,
    sections: [
      {
        id: 'section-1',
        title: 'Algebra & Functions',
        description: 'Algebraic equations, functions, and transformations',
        timePerQuestionMs: 120000, // 2 minutes per question
        totalQuestionsTarget: 10,
        questions: [
          {
            id: 'q1',
            topic: 'Quadratic Equations',
            text: 'Solve for x: x² + 5x + 6 = 0',
            options: ['x = -2, -3', 'x = 2, 3', 'x = -2, 3', 'x = 2, -3'],
            correctAnswer: 0,
            initialDifficulty: 'easy',
            explanation: 'Factoring: (x+2)(x+3) = 0, so x = -2 or x = -3',
          },
          {
            id: 'q2',
            topic: 'Functions',
            text: 'If f(x) = 2x² - 3x + 1, find f(-2)',
            options: ['11', '15', '19', '23'],
            correctAnswer: 2,
            initialDifficulty: 'easy',
            explanation: 'f(-2) = 2(-2)² - 3(-2) + 1 = 8 + 6 + 1 = 15',
          },
          {
            id: 'q3',
            topic: 'Domain and Range',
            text: 'What is the domain of f(x) = √(x-3)?',
            options: ['All real numbers', 'x ≥ 3', 'x > 3', 'x ≤ 3'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: 'The radicand must be non-negative, so x - 3 ≥ 0, thus x ≥ 3',
          },
          {
            id: 'q4',
            topic: 'Polynomial Division',
            text: 'Divide x³ + 2x² - 5x - 6 by (x - 2)',
            options: ['x² + 4x + 3', 'x² + 3x - 4', 'x² - 4x + 3', 'x² + 5x + 5'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: 'Using synthetic division: quotient is x² + 4x + 3',
          },
          {
            id: 'q5',
            topic: 'Composite Functions',
            text: 'If f(x) = x + 2 and g(x) = x², find (f ∘ g)(3)',
            options: ['11', '13', '15', '17'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: '(f ∘ g)(3) = f(g(3)) = f(9) = 9 + 2 = 11',
          },
          {
            id: 'q6',
            topic: 'Quadratic Equations',
            text: 'Find the vertex of f(x) = x² - 4x + 3',
            options: ['(2, -1)', '(1, -2)', '(2, -3)', '(-2, 3)'],
            correctAnswer: 0,
            initialDifficulty: 'hard',
            explanation: 'Vertex form: h = -b/2a = 4/2 = 2; f(2) = 4 - 8 + 3 = -1',
          },
          {
            id: 'q7',
            topic: 'Exponents',
            text: 'Simplify: (2x^3)(3x^2)',
            options: ['5x^5', '6x^6', '6x^5', '5x^6'],
            correctAnswer: 2,
            initialDifficulty: 'easy',
            explanation: 'Multiply coefficients and add exponents: 2*3 = 6 and x^(3+2) = x^5.',
          },
          {
            id: 'q8',
            topic: 'Functions',
            text: 'If f(x) = 3x - 2, solve f(x) = 13.',
            options: ['x = 3', 'x = 4', 'x = 5', 'x = 6'],
            correctAnswer: 2,
            initialDifficulty: 'easy',
            explanation: '3x - 2 = 13 -> 3x = 15 -> x = 5.',
          },
          {
            id: 'q9',
            topic: 'Inequalities',
            text: 'Solve: 2x - 7 > 5',
            options: ['x > 6', 'x < 6', 'x > -6', 'x < -6'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: '2x > 12 so x > 6.',
          },
          {
            id: 'q10',
            topic: 'Complex Numbers',
            text: 'Compute (3 + 2i) + (1 - 5i).',
            options: ['4 - 3i', '2 + 7i', '4 + 3i', '2 - 3i'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: 'Combine real and imaginary parts separately: 4 + (-3)i.',
          },
          {
            id: 'q11',
            topic: 'Rational Expressions',
            text: 'Simplify: (x^2 - 9)/(x - 3)',
            options: ['x - 3', 'x + 3', 'x^2 + 3', 'x^2 - 3'],
            correctAnswer: 1,
            initialDifficulty: 'hard',
            explanation: 'Factor numerator: (x-3)(x+3), then cancel x-3 where x != 3.',
          },
          {
            id: 'q12',
            topic: 'Logarithms',
            text: 'Solve for x: log10(x) = 2',
            options: ['10', '100', '1000', '2'],
            correctAnswer: 1,
            initialDifficulty: 'hard',
            explanation: 'If log10(x) = 2 then x = 10^2 = 100.',
          },
        ],
      },
      {
        id: 'section-2',
        title: 'Trigonometry',
        description: 'Trigonometric functions and identities',
        timePerQuestionMs: 120000,
        totalQuestionsTarget: 8,
        questions: [
          {
            id: 'trig1',
            topic: 'Basic Trigonometry',
            text: 'In a right triangle, if sin(θ) = 3/5, what is cos(θ)?',
            options: ['3/5', '4/5', '5/4', '5/3'],
            correctAnswer: 1,
            initialDifficulty: 'easy',
            explanation: 'Using the Pythagorean identity: sin²(θ) + cos²(θ) = 1; cos²(θ) = 1 - 9/25 = 16/25; cos(θ) = 4/5',
          },
          {
            id: 'trig2',
            topic: 'Trigonometric Identities',
            text: 'Simplify: sin(x)·csc(x)',
            options: ['sin(x)', '1', 'tan(x)', 'cos(x)'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: 'csc(x) = 1/sin(x), so sin(x)·csc(x) = sin(x)·(1/sin(x)) = 1',
          },
          {
            id: 'trig3',
            topic: 'Unit Circle',
            text: 'What is sin(30°)?',
            options: ['1/2', 'sqrt(3)/2', 'sqrt(2)/2', '1'],
            correctAnswer: 0,
            initialDifficulty: 'easy',
            explanation: 'On the unit circle, sin(30°) = 1/2.',
          },
          {
            id: 'trig4',
            topic: 'Unit Circle',
            text: 'What is cos(60°)?',
            options: ['1/2', 'sqrt(3)/2', '0', '1'],
            correctAnswer: 0,
            initialDifficulty: 'easy',
            explanation: 'On the unit circle, cos(60°) = 1/2.',
          },
          {
            id: 'trig5',
            topic: 'Trigonometric Equations',
            text: 'Solve on [0, 2pi): sin(x) = 0',
            options: ['x = 0, pi', 'x = pi/2, 3pi/2', 'x = pi/4, 5pi/4', 'x = 0 only'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: 'Sine is zero on the x-axis at angles 0 and pi in [0,2pi).',
          },
          {
            id: 'trig6',
            topic: 'Trigonometric Identities',
            text: 'Which identity is always true?',
            options: ['sin^2(x) + cos^2(x) = 1', 'sin(x) + cos(x) = 1', 'tan(x) = sin(x) + cos(x)', 'sec(x) = cos(x)'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: 'The Pythagorean identity holds for all x where defined.',
          },
          {
            id: 'trig7',
            topic: 'Inverse Trigonometry',
            text: 'Find theta if tan(theta) = 1 and 0 <= theta <= pi.',
            options: ['pi/4', 'pi/3', 'pi/6', '3pi/4'],
            correctAnswer: 0,
            initialDifficulty: 'hard',
            explanation: 'tan(pi/4) = 1 in the principal range.',
          },
          {
            id: 'trig8',
            topic: 'Trigonometric Graphs',
            text: 'The period of y = sin(2x) is:',
            options: ['2pi', 'pi', 'pi/2', '4pi'],
            correctAnswer: 1,
            initialDifficulty: 'hard',
            explanation: 'Period is 2pi/|b|, so 2pi/2 = pi.',
          },
        ],
      },
    ],
  },
  {
    id: 'english-201-essay',
    title: 'English Literature Quiz',
    description: 'Multiple choice questions on classic English literature',
    totalTimeMs: 60 * 60 * 1000, // 60 minutes
    adaptiveDifficulty: true,
    sections: [
      {
        id: 'lit-section-1',
        title: 'Classic Literature',
        description: 'Questions on classic literature and authors',
        timePerQuestionMs: 120000,
        totalQuestionsTarget: 10,
        questions: [
          {
            id: 'lit1',
            topic: 'Shakespeare',
            text: 'Who is the protagonist of "Hamlet"?',
            options: ['Claudius', 'Gertrude', 'Prince Hamlet', 'Ophelia'],
            correctAnswer: 2,
            initialDifficulty: 'easy',
            explanation: 'Prince Hamlet is the main character and protagonist of the play.',
          },
          {
            id: 'lit2',
            topic: 'Themes in Literature',
            text: 'Which theme is central to "The Great Gatsby"?',
            options: ['Revenge', 'The American Dream', 'Time Travel', 'Family Secrets'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: 'The pursuit and corruption of the American Dream is the central theme.',
          },
          {
            id: 'lit3',
            topic: 'Historical Context',
            text: 'When was "Jane Eyre" by Charlotte Brontë published?',
            options: ['1817', '1847', '1877', '1897'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: '"Jane Eyre" was published in 1847 under the pen name Currer Bell.',
          },
          {
            id: 'lit4',
            topic: 'Poetry',
            text: 'Who wrote "Paradise Lost"?',
            options: ['John Milton', 'Geoffrey Chaucer', 'William Blake', 'John Keats'],
            correctAnswer: 0,
            initialDifficulty: 'easy',
            explanation: 'John Milton authored the epic poem "Paradise Lost".',
          },
          {
            id: 'lit5',
            topic: 'Novels',
            text: 'Which novel begins with "Call me Ishmael"?',
            options: ['Moby-Dick', 'Wuthering Heights', 'Frankenstein', '1984'],
            correctAnswer: 0,
            initialDifficulty: 'easy',
            explanation: 'This famous opening line is from Herman Melville\'s "Moby-Dick".',
          },
          {
            id: 'lit6',
            topic: 'Drama',
            text: 'In "Macbeth," who persuades Macbeth to kill Duncan?',
            options: ['Banquo', 'Lady Macbeth', 'Macduff', 'The Witches'],
            correctAnswer: 1,
            initialDifficulty: 'medium',
            explanation: 'Lady Macbeth pressures and manipulates Macbeth into the murder.',
          },
          {
            id: 'lit7',
            topic: 'Literary Devices',
            text: 'An extended metaphor carried through a poem is called:',
            options: ['Conceit', 'Irony', 'Alliteration', 'Epitaph'],
            correctAnswer: 0,
            initialDifficulty: 'medium',
            explanation: 'A conceit is an elaborate or extended metaphor.',
          },
          {
            id: 'lit8',
            topic: 'Modernism',
            text: 'Which author wrote "Mrs Dalloway"?',
            options: ['Virginia Woolf', 'George Eliot', 'Mary Shelley', 'Doris Lessing'],
            correctAnswer: 0,
            initialDifficulty: 'hard',
            explanation: 'Virginia Woolf published "Mrs Dalloway" in 1925.',
          },
          {
            id: 'lit9',
            topic: 'Critical Reading',
            text: 'A narrator who cannot be fully trusted is called:',
            options: ['Omniscient narrator', 'Reliable narrator', 'Unreliable narrator', 'Objective narrator'],
            correctAnswer: 2,
            initialDifficulty: 'hard',
            explanation: 'The term is "unreliable narrator."',
          },
          {
            id: 'lit10',
            topic: 'Themes in Literature',
            text: 'Which theme best describes Orwell\'s "1984"?',
            options: ['Pastoral nostalgia', 'Totalitarian control', 'Romantic idealism', 'Magical realism'],
            correctAnswer: 1,
            initialDifficulty: 'hard',
            explanation: 'The novel explores surveillance, authoritarianism, and state control.',
          },
        ],
      },
    ],
  },
];

export function getSampleExam(examId: string): ExamConfiguration | undefined {
  return SAMPLE_EXAMS.find((exam) => exam.id === examId);
}

export function getAllSampleExams(): ExamConfiguration[] {
  return SAMPLE_EXAMS;
}
